# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Klb2DDs3K6wkYFSsOZl2JZg8cAsH44XR

File.txt
Welcome to py1
Welcome to py2
Welcome to py3
Welcome to py4

r+
"""

with open('file.txt', 'r+') as file1:
  file1.write("new word \n")

"""w+"""

with open('file.txt', 'w+') as f:   
    f.write("text 1\n")
    f.write("text 2\n")
    f.write("text 3\n")
    f.write("text 4\n")

"""Read and Write with w+"""

with open('file.txt', 'w+') as f: 
    f.write("HELLO \n")
    f.write("WELCOME \n")
    f.write("HI \n")
    f.write("HEY \n")           
    f.seek(0)                     
    lines = f.read() 
    print(lines)

"""a+"""

with open('file.txt', 'a+') as f:
    f.seek(0)                     
    lines = f.readlines()           
    f.write("\n" + str(len(lines)))

"""Tuple"""

# Empty tuple
my_tuple = ()
print(my_tuple)

# Tuple having integers
my_tuple = (1, 2, 3)
print(my_tuple)

# tuple with mixed datatypes
my_tuple = (1, "Hello", 3.4)
print(my_tuple)

# nested tuple
my_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(my_tuple)

"""Dictionary"""

# Creating an empty Dictionary
Dict = {}
print("Empty Dictionary: ")
print(Dict)
  
# Adding elements one at a time
Dict[0] = 'Geeks'
Dict[2] = 'For'
Dict[3] = 1
print("\nDictionary after adding 3 elements: ")
print(Dict)
  
# Adding set of values
# to a single Key
Dict['Value_set'] = 2, 3, 4
print("\nDictionary after adding 3 elements: ")
print(Dict)
  
# Updating existing Key's Value
Dict[2] = 'Welcome'
print("\nUpdated key value: ")
print(Dict)
  
# Adding Nested Key value to Dictionary
Dict[5] = {'Nested': {'1': 'Life', '2': 'Geeks'}}
print("\nAdding a Nested Key: ")
print(Dict)